## Cargando archivo

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/polla/Desktop/computo cognitivo/Bases de datos/amazon_alexa.tsv', delimiter ='\t' )

In [3]:
##Exploracion del archivo

In [4]:
pwd

'C:\\Users\\polla\\Desktop\\computo cognitivo'

In [5]:
data.shape

(3150, 5)

In [6]:
data.head(20)

,rating,date,variation,verified_reviews,feedback
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1
4,5,31-Jul-18,Charcoal Fabric,Music,1
5,5,31-Jul-18,Heather Gray Fabric,I received the echo as a gift. I needed anothe...,1
6,3,31-Jul-18,Sandstone Fabric,"Without having a cellphone, I cannot use many ...",1
7,5,31-Jul-18,Charcoal Fabric,I think this is the 5th one I've purchased. I'...,1
8,5,30-Jul-18,Heather Gray Fabric,looks great,1
9,5,30-Jul-18,Heather Gray Fabric,Love it! I’ve listened to songs I haven’t hear...,1
10,5,30-Jul-18,Charcoal Fabric,"I sent it to my 85 year old Dad, and he talks ...",1
11,5,30-Jul-18,Charcoal Fabric,I love it! Learning knew things with it eveyda...,1
12,5,30-Jul-18,Oak Finish,I purchased this for my mother who is having k...,1
13,5,30-Jul-18,Charcoal Fabric,"Love, Love, Love!!",1
14,5,30-Jul-18,Oak Finish,Just what I expected....,1
15,5,30-Jul-18,Heather Gray Fabric,"I love it, wife hates it.",1
16,5,30-Jul-18,Heather Gray Fabric,Really happy with this purchase. Great speake...,1
17,5,30-Jul-18,Heather Gray Fabric,We have only been using Alexa for a couple of ...,1
18,5,30-Jul-18,Charcoal Fabric,We love the size of the 2nd generation echo. S...,1
19,4,30-Jul-18,Sandstone Fabric,I liked the original Echo. This is the same bu...,1

In [7]:
data.dtypes

rating               int64
date                object
variation           object
verified_reviews    object
feedback             int64
dtype: object

In [8]:
data.isnull().sum()

rating              0
date                0
variation           0
verified_reviews    0
feedback            0
dtype: int64

In [9]:
data.describe()

            rating     feedback
count  3150.000000  3150.000000
mean      4.463175     0.918413
std       1.068506     0.273778
min       1.000000     0.000000
25%       4.000000     1.000000
50%       5.000000     1.000000
75%       5.000000     1.000000
max       5.000000     1.000000

In [10]:
data.describe(include = 'object')

             date   variation verified_reviews
count        3150        3150             3150
unique         77          16             2301
top     30-Jul-18  Black  Dot
freq         1603         516               79

## Generacion de variables

In [11]:
import  string
punctuation = string.punctuation
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [12]:
data['count_punctuation'] = data['verified_reviews'].apply(lambda x: len("". join(_ for _ in x if _ in punctuation)))

In [13]:
data['count_char'] = data['verified_reviews'].apply(len)

In [14]:
palabra = 'Hola 801, como estan?'

In [15]:
palabra.split()

['Hola', '801,', 'como', 'estan?']

In [16]:
data['count_word'] = data['verified_reviews'].apply(lambda x: len(x.split()))

In [17]:
data['density'] = data['count_char'] / (data['count_word'] + 1)

In [18]:
data.head(4)

,rating,date,variation,verified_reviews,feedback,count_punctuation,count_char,count_word,density
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1,1,13,3,3.250000
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1,1,9,2,3.000000
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1,3,195,38,5.000000
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1,4,172,34,4.914286

In [10]:
data.variation.value_counts()

Black  Dot                      516
Charcoal Fabric                 430
Configuration: Fire TV Stick    350
Black  Plus                     270
Black  Show                     265
Black                           261
Black  Spot                     241
White  Dot                      184
Heather Gray Fabric             157
White  Spot                     109
White                            91
Sandstone Fabric                 90
White  Show                      85
White  Plus                      78
Oak Finish                       14
Walnut Finish                     9
Name: variation, dtype: int64

## Polarizacion

In [11]:

from textblob import TextBlob

In [12]:
def c(x):
    return x*x

In [13]:
data['rr'] = data['rating'].apply(c)

In [14]:
data.head()

,rating,date,variation,verified_reviews,feedback,rr
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1,25
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1,25
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1,16
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1,25
4,5,31-Jul-18,Charcoal Fabric,Music,1,25

In [15]:
testimonial =TextBlob("Textblob is amazingly simple to use. What great fun!")

In [16]:
testimonial.sentiment.polarity

0.39166666666666666

In [17]:
def pol (text):
    text_blob =TextBlob(str(text.encode('utf-8')))
    pol = text_blob.sentiment.polarity
    return pol

In [18]:
texto = ("Textblob is amazingly simple to use. What great fun!")

In [19]:
pol(texto)

0.39166666666666666

In [20]:
data['polarity'] = data['verified_reviews'].apply(pol)

In [21]:
data.head(20)

,rating,date,variation,verified_reviews,feedback,rr,polarity
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1,25,0.625000
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1,25,0.875000
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1,16,-0.100000
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1,25,0.350000
4,5,31-Jul-18,Charcoal Fabric,Music,1,25,0.000000
5,5,31-Jul-18,Heather Gray Fabric,I received the echo as a gift. I needed anothe...,1,25,0.294643
6,3,31-Jul-18,Sandstone Fabric,"Without having a cellphone, I cannot use many ...",1,9,0.216667
7,5,31-Jul-18,Charcoal Fabric,I think this is the 5th one I've purchased. I'...,1,25,0.200000
8,5,30-Jul-18,Heather Gray Fabric,looks great,1,25,0.800000
9,5,30-Jul-18,Heather Gray Fabric,Love it! I’ve listened to songs I haven’t hear...,1,25,0.988281
10,5,30-Jul-18,Charcoal Fabric,"I sent it to my 85 year old Dad, and he talks ...",1,25,0.050000
11,5,30-Jul-18,Charcoal Fabric,I love it! Learning knew things with it eveyda...,1,25,0.403646
12,5,30-Jul-18,Oak Finish,I purchased this for my mother who is having k...,1,25,0.004167
13,5,30-Jul-18,Charcoal Fabric,"Love, Love, Love!!",1,25,0.593750
14,5,30-Jul-18,Oak Finish,Just what I expected....,1,25,-0.100000
15,5,30-Jul-18,Heather Gray Fabric,"I love it, wife hates it.",1,25,0.500000
16,5,30-Jul-18,Heather Gray Fabric,Really happy with this purchase. Great speake...,1,25,0.677778
17,5,30-Jul-18,Heather Gray Fabric,We have only been using Alexa for a couple of ...,1,25,0.121364
18,5,30-Jul-18,Charcoal Fabric,We love the size of the 2nd generation echo. S...,1,25,0.178125
19,4,30-Jul-18,Sandstone Fabric,I liked the original Echo. This is the same bu...,1,16,0.157222

In [38]:
data.sort_values(by=['polarity'])

,rating,date,variation,verified_reviews,feedback,rr,polarity,count,count_punctuation,count_char,count_word,density
1386,1,17-Jul-18,Black Spot,Invasive and scared the crap out of me for spe...,0,1,-1.000,1,1,88,18,4.631579
1340,1,19-Jul-18,Black Spot,Get rid of the &#34;Thongs To Try&#34; screen!...,0,1,-1.000,21,21,70,10,6.363636
661,1,24-May-18,Black,This Echo Dot is horrible. The volume on my ph...,0,1,-1.000,2,2,122,26,4.518519
1903,1,27-Jul-18,White Plus,Terrible. Stopped working after one day.,0,1,-1.000,2,2,40,6,5.714286
1487,2,30-Jul-18,White Show,Very disappointed. Alexa doesn’t hear me and ...,0,4,-0.975,2,2,77,12,5.923077
...,...,...,...,...,...,...,...,...,...,...,...,...
2902,5,30-Jul-18,Black Dot,Excellent. Bought another one yesterday!,1,25,1.000,2,2,40,5,6.666667
2836,5,30-Jul-18,Black Dot,Absolutely love it!!!!,1,25,1.000,4,4,22,3,5.500000
659,4,25-May-18,Black,Perfect,1,16,1.000,0,0,7,1,3.500000
1570,5,29-Jul-18,Black Show,Am very happy now that i can see.,1,25,1.000,1,1,33,8,3.666667
629,5,30-May-18,Black,I bought three of these and all three have wor...,1,25,1.000,3,3,122,21,5.545455

In [22]:
data[data['polarity']<0.3]

,rating,date,variation,verified_reviews,feedback,rr,polarity
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1,16,-0.100000
4,5,31-Jul-18,Charcoal Fabric,Music,1,25,0.000000
5,5,31-Jul-18,Heather Gray Fabric,I received the echo as a gift. I needed anothe...,1,25,0.294643
6,3,31-Jul-18,Sandstone Fabric,"Without having a cellphone, I cannot use many ...",1,9,0.216667
7,5,31-Jul-18,Charcoal Fabric,I think this is the 5th one I've purchased. I'...,1,25,0.200000
...,...,...,...,...,...,...,...
3138,5,30-Jul-18,White Dot,Este producto llegó y a la semana se quedó sin...,1,25,0.000000
3140,4,30-Jul-18,White Dot,Barry,1,16,0.000000
3141,3,30-Jul-18,Black Dot,,1,9,0.000000
3142,4,30-Jul-18,White Dot,My three year old loves it. Good for doing ba...,1,16,0.162857
3147,5,30-Jul-18,Black Dot,"I do love these things, i have them running my...",1,25,0.237662

## Ejercicio

filtrar los de polaridad menor a -0.7 y con mayor numero de palabras y describir cuales son las pricipales